spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_shop
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.tistory.johnmarc.jpashop.config.CustomNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibnerate:
        format_sql: true
    open-in-view: false
